#!/usr/bin/env python3
"""Generate INSERT statements for MegaHAL support data (ban/aux/grt/swp).

Reads plain-text data files from data/ and writes web/support-data.sql
with multi-row INSERT statements suitable for PGlite (no COPY FROM STDIN).
"""

import pathlib

PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
OUT_FILE = PROJECT_ROOT / "web" / "support-data.sql"


def read_wordlist(path: pathlib.Path) -> list[str]:
    """Read a file, skip comments (#) and blank lines, return words."""
    words = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        words.append(line)
    return words


def read_swap_pairs(path: pathlib.Path) -> list[tuple[str, str]]:
    """Read tab-separated swap pairs, handling multiple tabs."""
    pairs = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p for p in line.split("\t") if p]
        if len(parts) >= 2:
            pairs.append((parts[0], parts[1]))
    return pairs


def sql_escape(s: str) -> str:
    """Escape single quotes for SQL string literals."""
    return s.replace("'", "''")


def generate_insert(table: str, columns: list[str], rows: list[tuple]) -> str:
    """Generate a multi-row INSERT statement."""
    col_list = ", ".join(columns)
    value_rows = []
    for row in rows:
        vals = ", ".join(f"'{sql_escape(v)}'" for v in row)
        value_rows.append(f"  ({vals})")
    values = ",\n".join(value_rows)
    return f"INSERT INTO {table} ({col_list}) VALUES\n{values};\n"


def main():
    ban_words = read_wordlist(DATA_DIR / "megahal.ban")
    aux_words = read_wordlist(DATA_DIR / "megahal.aux")
    grt_words = read_wordlist(DATA_DIR / "megahal.grt")
    swp_pairs = read_swap_pairs(DATA_DIR / "megahal.swp")

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    parts = [
        "-- Auto-generated by scripts/generate-support-sql.py\n"
        "-- Do not edit manually.\n\n",
        generate_insert("banned_words", ["word"], [(w,) for w in ban_words]),
        "\n",
        generate_insert("aux_words", ["word"], [(w,) for w in aux_words]),
        "\n",
        generate_insert("greeting_words", ["word"], [(w,) for w in grt_words]),
        "\n",
        generate_insert("swap_pairs", ["from_word", "to_word"], swp_pairs),
    ]

    OUT_FILE.write_text("".join(parts))

    total = len(ban_words) + len(aux_words) + len(grt_words) + len(swp_pairs)
    print(f"Generated {OUT_FILE.relative_to(PROJECT_ROOT)} ({total} rows)")
    print(f"  banned_words:   {len(ban_words)} rows")
    print(f"  aux_words:      {len(aux_words)} rows")
    print(f"  greeting_words: {len(grt_words)} rows")
    print(f"  swap_pairs:     {len(swp_pairs)} rows")


if __name__ == "__main__":
    main()
